# Generated by Django 3.2.7 on 2021-09-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_media_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(default='https://picsum.photos/200', upload_to=''),
        ),
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
