# Generated by Django 3.2.7 on 2021-09-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210925_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.CharField(default='https://picsum.photos/200', max_length=50),
        ),
    ]
