# Generated by Django 3.2.7 on 2021-09-25 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_media_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
