# Generated by Django 3.2.7 on 2021-09-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_media_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='data',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
