# Generated by Django 3.2.7 on 2021-09-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_media_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='data',
            field=models.IntegerField(default=0),
        ),
    ]
